language: node_js
node_js:
- 6
cache:
  directories:
  - node_modules
script:
- yarn build
- sleep 1; echo done;
deploy:
  provider: heroku
  api_key:
    secure: Nfdk3uNa77GsUkx8LSVJ/fmKr06l+JThLhip+6w1+9mn6wRvFNOAgUV+15AeQKUs9EDsaEVVQ1pozmH2xE/sfEo0pvmRqXHOrD37VWhqDrE+b1YAqzA37bCMT4wLYR2KxsbTq0y2/M5OZonnCyzSrSA7d8UzmC1cl14GEvdLtQNxZM+Z3C2ty6yNEzqpwjitovq2x9deHQBx9+DgyMkoX7aaSfOTiY9EuU968vsBk+flVdcVgOZUAt45MSknLpy5nQiQisGim9cmDaFVLVtFwONLtzHBU9c06ybsjdy7J3hpB7uqd9+ZvAbO561VV6ZPp+jfH23b/S43M8oYgriotBeW289qlhvsS4MAafQKZ10urp0Ut+O0gXmoo3eX8b4BwYBl76FROBeyARhoL2mMKkOJ4QqEHUaklP7Ljdf282YnpwN4+n1rA9+NoFn1m6AvdDQj0ekPUQzRd4LUPShIu719hqe57A9+Nrp9mpF9B+EQFbfp17vfRKJb+k3Gl6fhmOIcti7H0HlNlEofGTkumjmmuGW3HduWEI7s91DLKPxgqDYa3qNrkmkGJmzUtMoz95RWWEH3zkWfpeoKZqh0PAYzRMFo/vnC8ITZfvUosKGzc7lwMOBuOkYozL0/EeHbXzFOcLH4GyUvho1yjGARL/VjxIzGxUyY8ck1L4qHcDU=
  app:
    master: react-redux-training
